The-Monitor-Dev/The-Monitor_BE

- src/main/java/the_monitor/application/service/UserService.java
- src/main/java/the_monitor/application/serviceImpl/UserServiceImpl.java
- src/main/java/the_monitor/domain/model/User.java
- src/main/java/the_monitor/domain/repository/UserRepository.java
- src/main/java/the_monitor/infrastructure/persistence/JpaUserRepository.java
- Set User Repository, Service, Entity
-
-
@JIHYUN2EE 
close #2
> [✨FEATURE] Set User Entity, Repository, Service

- .github/workflows/deploy.yml
- Dockerfile
- Set Deploy Files
- Deploy to EC2 instance using GitHub Action and Dockerfile
close #9
> [✨FEATURE] Deploy Setting

- .github/workflows/deploy.yml
- build.gradle
- src/main/java/the_monitor/common/Config/SwaggerConfig.java
- src/main/java/the_monitor/presentation/AccountController.java
- Swagger 코드 적용
- Swagger Config, Controller에 Swagger 어노테이션 적용
-
close #11
> [✨FEATURE] Adapt Swagger

- .github/workflows/deploy.yml
- build.gradle
- src/main/java/the_monitor/application/dto/request/AccountCreateRequest.java
- src/main/java/the_monitor/application/dto/request/AccountEmailCertifyRequest.java
- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/service/CertifiedKeyService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/CertifiedKeyServiceImpl.java
- src/main/java/the_monitor/common/Config/RedisConfig.java
- src/main/java/the_monitor/domain/model/Account.java
- src/main/java/the_monitor/domain/repository/AccountRepository.java
- src/main/java/the_monitor/infrastructure/jwt/JwtAuthenticationFilter.java
- src/main/java/the_monitor/infrastructure/security/SecurityConfig.java
- src/main/java/the_monitor/presentation/AccountController.java
- 회원가입 로직 수정
- 회원가입 플로우 기획에 변경에 따라 회원가입 로직 수정했습니다.
- 회원가입 이후 존재하던 이메일 인증 과정을 삭제하고, 회원가입 시 이메일 인증 코드를 통한 이메일 확인 과정이 추가되었습니다.
- 회원가입 인증 코드 관리를 위해 Redis 도입하였습니다.
- 인증 코드의 유효 시간은 10분으로 설정하였습니다.
close #13
> [✨FEATURE] Update new SignUp Process

- src/main/java/the_monitor/application/dto/request/AccountPasswordResetRequest.java
- src/main/java/the_monitor/application/dto/request/AccountSignInRequest.java
- src/main/java/the_monitor/application/dto/request/AccountSignUpRequest.java
- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/CertifiedKeyServiceImpl.java
- src/main/java/the_monitor/common/ApiException.java
- src/main/java/the_monitor/common/ErrorStatus.java
- src/main/java/the_monitor/common/ExceptionAdvice.java
- src/main/java/the_monitor/domain/model/Account.java
- src/main/java/the_monitor/domain/repository/AccountRepository.java
- src/main/java/the_monitor/infrastructure/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/the_monitor/infrastructure/jwt/JwtAuthenticationFilter.java
- src/main/java/the_monitor/infrastructure/jwt/JwtExceptionFilter.java
- src/main/java/the_monitor/infrastructure/security/SecurityConfig.java
- src/main/java/the_monitor/presentation/AccountController.java
- 로그인 로직 변경 및 비밀번호 재설정 로직 구현
- 로그인 시 검사하던 이메일 인증 여부를 제거하였습니다.
- Filter에서 이메일 인증 여부를 매번 확인하던 부분을 제거하였습니다.
- 비밀번호 재설정 로직 추가하였습니다.
-
close #15
> [✨FEATURE] Update new SignIn Process

- src/main/java/the_monitor/application/dto/request/AccountEmailRequest.java
- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/presentation/AccountController.java
/sendEmailConfirm and /sendPasswordChangeEmail http method was changed to Post
Related: #19
- /sendEmailConfirm and /sendPasswordChangeEmail http method 변경
- 둘 다 Get 요청에서 Post 요청으로 변경했습니다.
- AccountEmailRequest Dto 추가했습니다.
-
close #19
> [✨FEATURE] Update Controller Http Method

- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/CertifiedKeyServiceImpl.java
- src/main/java/the_monitor/common/ApiResponse.java
Place response message in ‘message’ on success, and optional data in ‘result’
Related:
- 응답 형식 수정
- 공통 응답(success, fail) : isSuccess, code, message
- Optional : result (response할 data가 있는 경우에만 optional하게 응답해줌)
-
close #21
> [♻️REFACTOR] Refactor Response Format

- src/main/java/the_monitor/application/serviceImpl/TemporaryPasswordGenerateServiceImpl.java
- src/main/java/the_monitor/domain/enums/CategoryType.java
- src/main/java/the_monitor/domain/enums/KeywordType.java
- src/main/java/the_monitor/domain/model/Account.java
- src/main/java/the_monitor/domain/model/Article.java
- src/main/java/the_monitor/domain/model/Category.java
- src/main/java/the_monitor/domain/model/Client.java
- src/main/java/the_monitor/domain/model/ClientMailCC.java
- src/main/java/the_monitor/domain/model/ClientMailRecipient.java
- src/main/java/the_monitor/domain/model/Keyword.java
- src/main/java/the_monitor/domain/model/Scrap.java
Domain_models are implemented
Related: #23
- Entity 세팅
- 위 ERD에 필요한 Entity 구성해놓았습니다.
- 보고서 관련된 Table 및 Entity는 아직 적용되지 않았으니, 추후 추가가 필요합니다.
close #23
> [🚀FEATURE] Entity Setting

- .github/workflows/deploy.yml
- src/main/java/the_monitor/application/dto/ArticleGoogleDto.java
- src/main/java/the_monitor/application/dto/ArticleNaverDto.java
- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/service/GoogleSearchService.java
- src/main/java/the_monitor/application/service/NaverSearchService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ArticleServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/GoogleSearchServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/NaverSearchServiceImpl.java
- src/main/java/the_monitor/common/Config/RestTemplateConfig.java
- src/main/java/the_monitor/domain/model/Article.java
- src/main/java/the_monitor/domain/repository/ArticleRepository.java
- src/main/java/the_monitor/infrastructure/persistence/JpaArticleRepository.java
- Google, Never Search API 연결해놨습니다.
- 임시로 7시가 되면 `dailyMonitoring()` 메서드가 실행되게 해놨습니다.
- dailyMonitoring()에서 naver 서비스, google 서비스단의 `saveArticlesFromNaver()`, `saveArticlesFromGoogle()` 메서드를 호출합니다.
- 각각의 서비스 클래스 안에는 OpenAPI에 필요한 정보와 Open API를 통해 얻을 수 있는 정보를 파싱하는 메서드가 담겨 있습니다.
- Open API마다 추출할 수 있는 정보가 다르기에, 클래스마다 파싱 메서드를 별도로 포함시켜놓았습니다.
- 중복 검사는 아직 적용시켜놓지 않았습니다. 현재 데이터를 저장하는 것은 자동으로 이루어지는데, 이후 test용 API를 만들어서 실행해본 뒤, 작동 결과 보고 적용할 예정입니다.
close #25
> [✨FEATURE] Implements Article Search

- src/main/java/the_monitor/application/dto/request/ClientRequest.java
- src/main/java/the_monitor/application/service/ClientService.java
- src/main/java/the_monitor/application/service/GoogleSearchService.java
- src/main/java/the_monitor/application/service/NaverSearchService.java
- src/main/java/the_monitor/application/serviceImpl/ArticleServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/GoogleSearchServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/NaverSearchServiceImpl.java
- src/main/java/the_monitor/common/Config/SwaggerConfig.java
- src/main/java/the_monitor/domain/model/Category.java
- src/main/java/the_monitor/domain/model/Keyword.java
- src/main/java/the_monitor/domain/repository/CategoryRepository.java
- src/main/java/the_monitor/domain/repository/ClientMailCCRepository.java
- src/main/java/the_monitor/domain/repository/ClientMailRecipientRepository.java
- src/main/java/the_monitor/domain/repository/ClientRepository.java
- src/main/java/the_monitor/domain/repository/KeywordRepository.java
- src/main/java/the_monitor/presentation/ClientController.java
> [Feat] create main page

- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/infrastructure/jwt/JwtAuthenticationFilter.java
- src/main/java/the_monitor/infrastructure/jwt/JwtProvider.java
- src/main/java/the_monitor/infrastructure/security/SecurityConfig.java
- src/main/java/the_monitor/presentation/AccountController.java
- JWT 토큰 방식을 변경해보았습니다.
-
-
#34 
#33
> JWT TOKEN STORAGE METHOD UPDATE

- src/main/java/the_monitor/application/dto/ArticleGoogleDto.java
- src/main/java/the_monitor/application/dto/request/ArticleRequest.java
- src/main/java/the_monitor/application/dto/request/ArticleSearchRequest.java
- src/main/java/the_monitor/application/dto/response/ArticleResponse.java
- src/main/java/the_monitor/application/service/ArticleService.java
- src/main/java/the_monitor/application/service/GoogleSearchService.java
- src/main/java/the_monitor/application/service/KeywordService.java
- src/main/java/the_monitor/application/serviceImpl/ArticleServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/GoogleSearchServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/KeywordServiceImpl.java
- src/main/java/the_monitor/common/PageResponse.java
- src/main/java/the_monitor/domain/model/Keyword.java
- src/main/java/the_monitor/domain/repository/ArticleRepository.java
- src/main/java/the_monitor/domain/repository/KeywordRepository.java
- src/main/java/the_monitor/infrastructure/jwt/JwtProvider.java
- src/main/java/the_monitor/infrastructure/security/CustomUserDetails.java
- src/main/java/the_monitor/presentation/ArticleController.java
> [✨FEATURE] Implement daily monitoring functions

- src/main/java/the_monitor/application/service/ArticleService.java
- src/main/java/the_monitor/presentation/ArticleController.java
> fix: article 에러 수정

- src/main/java/the_monitor/presentation/ArticleController.java
> fix: article 주석 처리

- src/main/java/the_monitor/application/service/ArticleService.java
- src/main/java/the_monitor/presentation/ArticleController.java
> articlecontroller 부분 주석 처리

- src/main/java/the_monitor/domain/repository/ArticleRepository.java
- 주석 처리 되어 있던 곳 다시 복구시켰습니다
-
-
> fix: articlerepository 수정

- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
> fix: 주석 수정

- src/main/java/the_monitor/TheMonitorApplication.java
- src/main/java/the_monitor/domain/repository/ArticleRepository.java
- s3 Iam 환경설정으로 인한 변경
- jpa, jdbc 어노테이션 작성
-
-
> fix: s3 환경설정 및 repository 어노테이션 수정

- .github/workflows/deploy.yml
> add: deploy.yml 환경변수 gitsecret에 추가

- .github/workflows/deploy.yml
- deploy.yml 환경변수 git secrets에 추가
-
-
> deploy.yml 환경변수 git secrets에 추가

- src/main/java/the_monitor/domain/repository/ArticleRepository.java
> fix: 주석 다시 처리

- src/main/java/the_monitor/domain/model/Account.java
- 순환 참조 문제 해결을 위해 @JsonIgnore 추가
-
-
> fix: 순환 참조 문제 해결

- build.gradle
- src/main/java/the_monitor/TheMonitorApplication.java
- src/main/java/the_monitor/application/serviceImpl/GoogleSearchServiceImpl.java
- .env 파일을 통해 환경변수 관리를 하려 하였으나, .env 배포의 어려움과 보안상의 우려로 인해 .env 파일 적용하려던 것은 취소하였습니다.
- 대신 로컬 환경에서 실행하여 테스트 해볼 수 있도록 코드를 수정했습니다.
- JIB 코드 변경
-
close #29
> [✨FEATURE] Apply .env file

- src/main/java/the_monitor/application/dto/response/ClientResponse.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- clientresponse에 keyword 추가
-
-
> fix: ClientResponse keyword 추가

- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/infrastructure/jwt/JwtProvider.java
- src/main/java/the_monitor/infrastructure/security/SecurityConfig.java
- src/main/java/the_monitor/presentation/AccountController.java
> feat: 토큰 유효성 검사 추가

- src/main/java/the_monitor/application/dto/response/ClientResponse.java
- src/main/java/the_monitor/application/service/ClientService.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/common/ErrorStatus.java
- src/main/java/the_monitor/domain/repository/ClientRepository.java
- src/main/java/the_monitor/presentation/ClientController.java
- 고객사 리스트를 조회하기 위한 기능을 추가하였습니다
-
-
#70
> feat: 고객사 리스트 조회

- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/presentation/AccountController.java
- 토큰 유효성 검사를 위한 기능을 추가하였습니다. 
-
-
close #75
> feature: 토큰 유효성 검사 기능

- src/main/java/the_monitor/application/service/ReportService.java
- src/main/java/the_monitor/application/serviceImpl/ReportServiceImpl.java
- src/main/java/the_monitor/domain/repository/ReportRepository.java
- src/main/java/the_monitor/presentation/ReportController.java
- 보고서 관리에서 부가 기능 구현했습니다.
- 보고서 검색 기능 구현
- 보고서 기사 삭제 기능 구현
- 보고서 검색은 기본값으로 최근 생성일순으로 해두었습니다. 기획팀에서 수정일 순으로 정렬하는 것도 필요하다 답변 오면 추가하겠습니다.
@JIHYUN2EE 
close #79
> [✨FEATURE] Implement Additional Functions For Report Management

- src/main/java/the_monitor/application/dto/request/ClientRequest.java
- src/main/java/the_monitor/application/dto/response/ClientResponse.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/KeywordServiceImpl.java
- src/main/java/the_monitor/domain/model/Keyword.java
- src/main/java/the_monitor/domain/repository/ClientRepository.java
- src/main/java/the_monitor/domain/repository/KeywordRepository.java
- 고객사 입력 카테고리 수정
- 빈 배열 반환
-
-
close #83
> feat: 고객사 입력 수정

- src/main/java/the_monitor/application/dto/request/ClientRequest.java
- src/main/java/the_monitor/application/dto/request/EmailUpdateRequest.java
- src/main/java/the_monitor/application/dto/request/KeywordUpdateRequest.java
- src/main/java/the_monitor/application/dto/response/EmailResponse.java
- src/main/java/the_monitor/application/service/CategoryService.java
- src/main/java/the_monitor/application/service/EmailService.java
- src/main/java/the_monitor/application/service/KeywordService.java
- src/main/java/the_monitor/application/serviceImpl/CategoryServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/EmailServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/KeywordServiceImpl.java
- src/main/java/the_monitor/domain/repository/ClientMailCCRepository.java
- src/main/java/the_monitor/domain/repository/ClientMailRecipientRepository.java
- src/main/java/the_monitor/domain/repository/KeywordRepository.java
- src/main/java/the_monitor/presentation/EmailController.java
- src/main/java/the_monitor/presentation/KeywordController.java
- 재사용성을 위한 CategoryService, EmailService로 분리
-
-
close #87
> Feature: 키워드 및 이메일 설정

- src/main/java/the_monitor/application/dto/request/ClientRequest.java
- src/main/java/the_monitor/domain/enums/CategoryType.java
- src/main/java/the_monitor/presentation/ClientController.java
- src/main/java/the_monitor/presentation/EmailController.java
- src/main/java/the_monitor/presentation/KeywordController.java
> fix: 오타 및 피드백 수정

- .github/workflows/deploy.yml
- docker-compose.yml
- nginx.conf
- 배포 파일 추가
- docker-compose 적용
- NGINX 적용
-
@JIHYUN2EE 
close #89
> [🚀 DEPLOY] Adapt Docker Compose and NGINX For HTTPS

- src/main/java/the_monitor/application/dto/request/ClientRequest.java
- src/main/java/the_monitor/application/dto/response/EmailResponse.java
- src/main/java/the_monitor/application/service/EmailService.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/EmailServiceImpl.java
- src/main/java/the_monitor/common/Config/S3Config.java
- src/main/java/the_monitor/domain/model/Client.java
- src/main/java/the_monitor/domain/model/Signature.java
- src/main/java/the_monitor/domain/repository/SignatureRepository.java
- src/main/java/the_monitor/presentation/ClientController.java
- src/main/java/the_monitor/presentation/EmailController.java
- 이미지 업로드 부분에 에러가 있어서 해결했어요. 
PASCAL_CASE_TO_CAMEL_CASE 이 에러가 계속 발생해서 이 아래 블로그 참고했습니다.
- https://prohannah.tistory.com/87
- https://velog.io/@rhqjatn2398/spring.jackson.property-naming-strategy-%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC
-
close #94
> feat: 이미지 업로드 기능 구현

- src/main/java/the_monitor/application/dto/request/ClientRequest.java
- src/main/java/the_monitor/application/dto/response/EmailResponse.java
- src/main/java/the_monitor/application/service/EmailService.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/EmailServiceImpl.java
- src/main/java/the_monitor/common/Config/S3Config.java
- src/main/java/the_monitor/domain/model/Client.java
- src/main/java/the_monitor/domain/model/Signature.java
- src/main/java/the_monitor/domain/repository/SignatureRepository.java
- src/main/java/the_monitor/presentation/ClientController.java
- src/main/java/the_monitor/presentation/EmailController.java
> [Feature] Image Upload

- src/main/java/the_monitor/application/service/ClientService.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/presentation/ClientController.java
- 클라이언트 id로 정보 조회하는 api를 구현하였습니다.
-
-
@L-U-Ready 
close #97
> Feat: 클라이언트 id로 정보 조회

- src/main/java/the_monitor/application/serviceImpl/ReportServiceImpl.java
- src/main/java/the_monitor/domain/model/Report.java
- 보고서 생성에서 발생한 에러 해결했습니다.
- 보고서 생성 시 에러가 발생한 이유가 logo file이 null로 들어오면서 발생한 문제라고 생각했는데, 
```
public void addReportArticle(ReportArticle reportArticle) {
this.reportArticle.add(reportArticle);
}
```
로 추가하고 있었기 때문에 문제가 발생했습니다.
첨부 이미지와 같이 List<ReportArticle> reportArticle로 받고, this.reportArticle = reportArticle;을 해주니 해결되었습니다.
@JIHYUN2EE 
close #106
> [🐛 FIX] Resolving Report Generation Errors

- src/main/java/the_monitor/application/dto/request/ClientUpdateRequest.java
- src/main/java/the_monitor/application/service/ClientService.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ReportServiceImpl.java
- src/main/java/the_monitor/common/ErrorStatus.java
- src/main/java/the_monitor/domain/model/Client.java
- src/main/java/the_monitor/presentation/ClientController.java
- 고객사 정보 수정 및 삭제 기능 구현했습니다.
-
-
close #109
> Feat: 고객사 정보 수정 및 삭제

- src/main/java/the_monitor/application/dto/response/KeywordResponse.java
- src/main/java/the_monitor/application/service/KeywordService.java
- src/main/java/the_monitor/application/serviceImpl/KeywordServiceImpl.java
- src/main/java/the_monitor/presentation/KeywordController.java
- Change Keyword List Response Format 
- 프론트 요청에 따라 CategoryType을 명시적으로 나타내던 것을 수정하였습니다.
-
@JIHYUN2EE 
close #111
> [♻️ REFACTOR] Change Keyword List Response Format

- src/main/java/the_monitor/application/serviceImpl/ReportServiceImpl.java
- 보고서 검색 UpdatedAt 에러 해결
- 보고서 검색 시 UpdatedAt Field가 null로 뜨는 에러가 있어서 해결했습니다.
-
@JIHYUN2EE 
close #115
> [🐛 FIX] Change UpdatedAt Field Error Resolution When Report Search 

- src/main/java/the_monitor/application/dto/request/EmailSendRequest.java
- src/main/java/the_monitor/application/dto/response/EmailSendResponse.java
- src/main/java/the_monitor/application/service/EmailService.java
- src/main/java/the_monitor/application/serviceImpl/EmailServiceImpl.java
- src/main/java/the_monitor/presentation/EmailController.java
- 수신자, 참조인에게 이메일 보내는 기능을 구현했습니다.
- 아직 파일 추출 기능이 되어있지 않아서, 먼저 메일 전송만 구현했고 추후에 추가하겠습니다.
-
@L-U-Ready 
close #117
> Feature: 이메일 전송 기능 구현

- src/main/java/the_monitor/application/dto/request/ReportSearchTitleRequest.java
- src/main/java/the_monitor/application/service/ReportService.java
- src/main/java/the_monitor/application/serviceImpl/ReportServiceImpl.java
- src/main/java/the_monitor/presentation/ReportController.java
- 보고서 내용을 메일로 전송하는 기능을 구현했습니다.
- 엑셀 파일 추출 기능이 아직 구현되어 있지 않아서, 추후 추가하겠습니다.
-
#117 #119
> Feat: 메일 전송하기

- src/main/java/the_monitor/application/service/ClientService.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/domain/repository/ClientRepository.java
- src/main/java/the_monitor/presentation/ClientController.java
- 고객사 이름 검색 기능 구현했습니다. 
-
-
@L-U-Ready 
close #122
> Feature: 고객사 이름 검색 기능 구현

- src/main/java/the_monitor/application/dto/request/SearchRequest.java
- src/main/java/the_monitor/application/serviceImpl/ClientServiceImpl.java
- src/main/java/the_monitor/domain/repository/ClientRepository.java
- src/main/java/the_monitor/presentation/ClientController.java
- client 검색이 모든 경우 되는 것을 해당 고객사의 client일 때만 검색되는 것으로 수정했습니다.
-
-
@L-U-Ready 
closer #132
> Fix: 고객사 검색 오류 수정

- src/main/java/the_monitor/application/service/AccountService.java
- src/main/java/the_monitor/application/serviceImpl/AccountServiceImpl.java
- src/main/java/the_monitor/common/ApiResponse.java
- src/main/java/the_monitor/common/Config/WebConfig.java
- src/main/java/the_monitor/presentation/AccountController.java
> Fix: 프론트 요구사항 수정

- src/main/java/the_monitor/application/dto/ArticleGoogleDto.java
- src/main/java/the_monitor/application/dto/ScrapArticleDto.java
- src/main/java/the_monitor/application/service/ScrapService.java
- src/main/java/the_monitor/application/serviceImpl/ArticleServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ScrapServiceImpl.java
- src/main/java/the_monitor/domain/model/Article.java
- src/main/java/the_monitor/domain/repository/ArticleRepository.java
- src/main/java/the_monitor/presentation/ScrapController.java
> Feat: 스크랩 기능 수정

- src/main/java/the_monitor/application/dto/response/ReportListResponse.java
- src/main/java/the_monitor/application/serviceImpl/ReportServiceImpl.java
- 밀리세컨초를 제외하고 반환하는 것으로 변경했습니다.
-
-
> Response 변경

- src/main/java/the_monitor/application/service/ScrapService.java
- src/main/java/the_monitor/application/serviceImpl/ScrapServiceImpl.java
- src/main/java/the_monitor/domain/repository/ScrapRepository.java
- src/main/java/the_monitor/presentation/ScrapController.java
> Fix: 스크랩 로직 수정

- src/main/java/the_monitor/application/service/EmailService.java
- src/main/java/the_monitor/application/service/ExcelService.java
- src/main/java/the_monitor/application/serviceImpl/EmailServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ExcelServiceImpl.java
- src/main/java/the_monitor/common/ErrorStatus.java
- src/main/java/the_monitor/presentation/EmailController.java
- 이메일 전송하기 누를 때, 바로 엑셀 추출해서 포함해서 반환하게 한다.
-
-
> Feat: 엑셀 추출 및 이메일 전송

- src/main/java/the_monitor/application/service/EmailService.java
- src/main/java/the_monitor/application/service/ExcelService.java
- src/main/java/the_monitor/application/serviceImpl/EmailServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/ExcelServiceImpl.java
- src/main/java/the_monitor/application/serviceImpl/GoogleSearchServiceImpl.java
- src/main/java/the_monitor/common/ErrorStatus.java
- src/main/java/the_monitor/presentation/EmailController.java
- 이메일로 전송하기 할 때, 엑셀이 추출되어 첨부됨.
-
-
> Feat: 이메일 내보내기 
